import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { RootStyleRegistry } from "@/components/RootStyleRegistry";
import BaseLayout from "@/components/layout/BaseLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App Blog",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  children: React.ReactNode
  auth: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ margin: 0 }}>
        <RootStyleRegistry>
          <BaseLayout>
            {props.children}
            {props.auth}
          </BaseLayout>
        </RootStyleRegistry>
      </body>
    </html>
  );
}
